version: "3"
services:
  my_app:
    image: my_app
    ports:
      - "8090:8888"
    networks:
      - myNetwork
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb/bootdb?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql=true" : "true"
      }'
 
  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - myNetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    volumes:
      - my-db:/var/lib/mysql

networks:
  myNetwork:
volumes:
  my-db: 